export { commit } from './git/commit';
export { configUser } from './git/config-user';
export { initProject } from './git/init-project';
export { isGitConfigured } from './git/is-git-configured';
export * from './remrg-installed';
export { mergeTemplate } from './merge-template';
export { replacePlaceholder } from './replace-placeholder';
export { stage } from './git/stage';
export { writePlaceholdersYaml } from './write-placeholders-yaml';
export { writeTemplateYaml } from './write-template-yaml';
